<?xml version="1.0" ?><root>
<report><version>2</version><sessionid>66d125c11dc02a5666ce2c2a</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-08-27 21:43:17</createtime><buildsignature>Local.Unknown.Unknown.1.108.349.1020-1.300.000.189.Release</buildsignature><categoryid>Lumpinou_LifeMilsetones_Injections.py:7</categoryid><desyncid>66d125c11dc02a5666ce2c2a</desyncid><systemconfig/><screenshot/><desyncdata>  Failure: 'Lumpinou_LifeMilsetones_Injections' (Lumpinou_LifeMilsetones_Injections) &#13;&#10;     No module named 'relationships.relationship_data' (ModuleNotFoundError: No module named 'relationships.relationship_data')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\importer\utils.py", line 120, in import_modules_by_path&#13;&#10;  File "&lt;frozen importlib._bootstrap&gt;", line 983, in _find_and_load&#13;&#10;  File "&lt;frozen importlib._bootstrap&gt;", line 967, in _find_and_load_unlocked&#13;&#10;  File "&lt;frozen importlib._bootstrap&gt;", line 668, in _load_unlocked&#13;&#10;  File "&lt;frozen importlib._bootstrap&gt;", line 638, in _load_backward_compatible&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\importer\custom_import.py", line 196, in load_module&#13;&#10;  File "C:\Sims 4 Python Script Workspace (3.7)\My Script Mods\LifeMilestones\Scripts\Lumpinou_LifeMilsetones_Injections.py", line 7, in &lt;module&gt;&#13;&#10;ModuleNotFoundError: No module named 'relationships.relationship_data'rtim=0&#13;&#10;Client Session Time: 36.04&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,280,0,5793&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>66d125c11dc02a5666ce2c2a</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-08-27 21:43:17</createtime><buildsignature>Local.Unknown.Unknown.1.108.349.1020-1.300.000.189.Release</buildsignature><categoryid>Lumpinou_LifeMilsetones_Injections.py:7</categoryid><desyncid>66d125c11dc02a5666ce2c2a</desyncid><systemconfig/><screenshot/><desyncdata>  Failure: 'Lumpinou_LifeMilsetones_Injections' (Lumpinou_LifeMilsetones_Injections) &#13;&#10;     No module named 'relationships.relationship_data' (ModuleNotFoundError: No module named 'relationships.relationship_data')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\importer\utils.py", line 120, in import_modules_by_path&#13;&#10;  File "&lt;frozen importlib._bootstrap&gt;", line 983, in _find_and_load&#13;&#10;  File "&lt;frozen importlib._bootstrap&gt;", line 967, in _find_and_load_unlocked&#13;&#10;  File "&lt;frozen importlib._bootstrap&gt;", line 668, in _load_unlocked&#13;&#10;  File "&lt;frozen importlib._bootstrap&gt;", line 638, in _load_backward_compatible&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\importer\custom_import.py", line 196, in load_module&#13;&#10;  File "C:\Sims 4 Python Script Workspace (3.7)\My Script Mods\LifeMilestones\Scripts\Lumpinou_LifeMilsetones_Injections.py", line 7, in &lt;module&gt;&#13;&#10;ModuleNotFoundError: No module named 'relationships.relationship_data'rtim=0&#13;&#10;Client Session Time: 36.04&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,280,0,5793&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>66d125c11dc02a5666ce2c2a</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-08-27 21:43:18</createtime><buildsignature>Local.Unknown.Unknown.1.108.349.1020-1.300.000.189.Release</buildsignature><categoryid>Lumpinou_RPO3_Injections.py:12</categoryid><desyncid>66d125c11dc02a5666ce2c2a</desyncid><systemconfig/><screenshot/><desyncdata>  Failure: 'Lumpinou_RPO3_Injections' (Lumpinou_RPO3_Injections) &#13;&#10;     No module named 'relationships.relationship_data' (ModuleNotFoundError: No module named 'relationships.relationship_data')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\importer\utils.py", line 120, in import_modules_by_path&#13;&#10;  File "&lt;frozen importlib._bootstrap&gt;", line 983, in _find_and_load&#13;&#10;  File "&lt;frozen importlib._bootstrap&gt;", line 967, in _find_and_load_unlocked&#13;&#10;  File "&lt;frozen importlib._bootstrap&gt;", line 668, in _load_unlocked&#13;&#10;  File "&lt;frozen importlib._bootstrap&gt;", line 638, in _load_backward_compatible&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\importer\custom_import.py", line 196, in load_module&#13;&#10;  File "C:\Sims 4 Python Script Workspace (3.7)\My Script Mods\RelationshipPregnancyOverhaulCollection\Scripts\Lumpinou_RPO3_Injections.py", line 12, in &lt;module&gt;&#13;&#10;ModuleNotFoundError: No module named 'relationships.relationship_data'rtim=0&#13;&#10;Client Session Time: 36.04&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,280,0,5793&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>66d125c11dc02a5666ce2c2a</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-08-27 21:43:18</createtime><buildsignature>Local.Unknown.Unknown.1.108.349.1020-1.300.000.189.Release</buildsignature><categoryid>Lumpinou_RPO3_RelRomTweaks.py:18</categoryid><desyncid>66d125c11dc02a5666ce2c2a</desyncid><systemconfig/><screenshot/><desyncdata>  Failure: 'Lumpinou_RPO3_RelRomTweaks' (Lumpinou_RPO3_RelRomTweaks) &#13;&#10;     No module named 'relationships.relationship_data' (ModuleNotFoundError: No module named 'relationships.relationship_data')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\importer\utils.py", line 120, in import_modules_by_path&#13;&#10;  File "&lt;frozen importlib._bootstrap&gt;", line 983, in _find_and_load&#13;&#10;  File "&lt;frozen importlib._bootstrap&gt;", line 967, in _find_and_load_unlocked&#13;&#10;  File "&lt;frozen importlib._bootstrap&gt;", line 668, in _load_unlocked&#13;&#10;  File "&lt;frozen importlib._bootstrap&gt;", line 638, in _load_backward_compatible&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\importer\custom_import.py", line 196, in load_module&#13;&#10;  File "C:\Sims 4 Python Script Workspace (3.7)\My Script Mods\RelationshipPregnancyOverhaulCollection\Scripts\Lumpinou_RPO3_RelRomTweaks.py", line 18, in &lt;module&gt;&#13;&#10;ModuleNotFoundError: No module named 'relationships.relationship_data'rtim=0&#13;&#10;Client Session Time: 36.04&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,280,0,5793&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
</root>