<?xml version="1.0" ?><root>
<BetterExceptions><BEversion>v3.11</BEversion><WasBlank>False</WasBlank><TuningLoadFinished>True</TuningLoadFinished><BadObjectCC>False</BadObjectCC><Advice>Not available. More info may be in BE Report.</Advice></BetterExceptions><report><version>2</version><sessionid>1c3ef420837e7b14656dcebc</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2023-12-04 14:43:21</createtime><buildsignature>Local.Unknown.Unknown.1.102.190.1030-1.200.000.609.Release</buildsignature><categoryid>aspiration_tuning.py:818</categoryid><desyncid>1c3ef420837e7b14656dcebc</desyncid><systemconfig/><screenshot/><desyncdata>[BE Interceptor] BE intercepted this error from a separate mod log so that it can scan for the issue. (IndexError: tuple index out of range)&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 217, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v176i\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v176i\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 507, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 260, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\aging\aging_mixin.py", line 526, in callback_auto_age&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\aging\aging_mixin.py", line 545, in age_moment&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\aging\aging_mixin.py", line 589, in _age_up_pctya&#13;&#10;  File "E:\Builds\MCCC_2023_6_0\mc_cmd_center\mc_utils.py", line 202, in _wrapper_function&#13;&#10;  File "E:\Builds\MCCC_2023_6_0\mc_cmd_center\mc_injections.py", line 334, in inject_advance_age&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\aging\aging_mixin.py", line 838, in advance_age&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\aspirations\aspiration_tuning.py", line 818, in is_valid_for_sim&#13;&#10;IndexError: tuple index out of rangertim=0&#13;&#10;Client Session Time: 26.57&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,74,0,5587&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>1c3ef420837e7b14656dcebc</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2023-12-04 15:20:41</createtime><buildsignature>Local.Unknown.Unknown.1.102.190.1030-1.200.000.609.Release</buildsignature><categoryid>flauschtrud_neighborhoodstories_marriage.py:226</categoryid><desyncid>1c3ef420837e7b14656dcebc</desyncid><systemconfig/><screenshot/><desyncdata>Exception while updating story progression service.:  (TypeError: can only concatenate list (not "NoneType") to list)&#13;&#10;Traceback (most recent call last):&#13;&#10;Caught and logged:&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\story_progression\story_progression_tracker.py", line 139, in update_arcs_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\story_progression\story_progression_arc.py", line 154, in update_story_arc&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\story_progression\story_progression_chapter.py", line 201, in update_story_chapter&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\story_progression\story_progression_actions\story_progression_action_base.py", line 52, in run_story_progression_action&#13;&#10;  File "J:\flauschtrud\Documents\USB Backup\Python Workspace\My Script Mods\NeighborhoodStoriesMarriage\Scripts\flauschtrud_neighborhoodstories_marriage.py", line 226, in _run_story_progression_action&#13;&#10;TypeError: can only concatenate list (not "NoneType") to listrtim=0&#13;&#10;Client Session Time: 26.57&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,74,0,5587&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>1c3ef420837e7b14656dcebc</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2023-12-04 15:36:20</createtime><buildsignature>Local.Unknown.Unknown.1.102.190.1030-1.200.000.609.Release</buildsignature><categoryid>funds.py:97</categoryid><desyncid>1c3ef420837e7b14656dcebc</desyncid><systemconfig/><screenshot/><desyncdata>Exception while generating potential interactions for object_barProC2x1_01:0x06cc11ef741162e1: (AttributeError: 'NoneType' object has no attribute 'family_funds')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\crafting\crafting_interactions.py", line 1174, in picker_rows_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\crafting\crafting_process.py", line 481, in recipe_test_price&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\crafting\crafting_process.py", line 443, in _get_price_error_list&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\payment\payment_source.py", line 95, in max_funds&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\funds.py", line 97, in get_funds_for_source&#13;&#10;AttributeError: 'NoneType' object has no attribute 'family_funds'rtim=0&#13;&#10;Client Session Time: 26.57&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,74,0,5587&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
</root>