<?xml version="1.0" ?><root>
<BetterExceptions><BEversion>v3.11</BEversion><WasBlank>False</WasBlank><TuningLoadFinished>True</TuningLoadFinished><BadObjectCC>False</BadObjectCC><Advice>Not available. More info may be in BE Report.</Advice></BetterExceptions><report><version>2</version><sessionid>60e35d90e5429f2765a43ce8</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-14 21:06:07</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>60e35d90e5429f2765a43ce8</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\commands.py", line 399, in invoke_command&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server_commands\ui_commands.py", line 29, in ui_dialog_respond&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\ui\ui_dialog_service.py", line 211, in dialog_respond&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\ui\ui_dialog.py", line 513, in respond&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\callback_utils.py", line 158, in __call__&#13;&#10;  File "E:\Builds\MCCC_2023_7_1\mc_cmd_center\mc_cmd_center.py", line 497, in get_ok_cancel&#13;&#10;  File "E:\Builds\MCCC_2023_7_1\mc_cmd_center\mc_utils.py", line 538, in delete_sim_and_household&#13;&#10;  File "E:\Builds\MCCC_2023_7_1\mc_cmd_center\mc_utils.py", line 555, in permanently_delete_sim&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info_manager.py", line 995, in remove_permanently&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File ".\WickedWhims_v177c\turbolib2\events\objects.py", line 107, in _turbolib_object_manager_remove&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\object_manager.py", line 161, in remove&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\indexed_manager.py", line 255, in remove&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\indexed_manager.py", line 343, in call_on_remove&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 83, in wrapped_method&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 991, in on_remove&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1057, in remove_selectable_sim_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.81&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>60e35d90e5429f2765a43ce8</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-14 21:07:31</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>60e35d90e5429f2765a43ce8</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 260, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduler.py", line 321, in _alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2298, in _start_work_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2889, in start_new_career_session&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 899, in resend_at_work_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.81&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>60e35d90e5429f2765a43ce8</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-14 21:25:44</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>60e35d90e5429f2765a43ce8</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 260, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2811, in _end_work_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3246, in leave_work&#13;&#10;  File "E:\Builds\MCCC_2023_7_1\mc_cmd_center\mc_utils.py", line 202, in _wrapper_function&#13;&#10;  File "E:\Builds\MCCC_2023_7_1\mc_cmd_center\mc_injections.py", line 1123, in inject_end_career_session&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3042, in end_career_session&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 899, in resend_at_work_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.81&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>60e35d90e5429f2765a43ce8</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-14 21:26:46</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>60e35d90e5429f2765a43ce8</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 224, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 593, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 608, in _call_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.81&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>60e35d90e5429f2765a43ce8</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-14 21:27:25</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>60e35d90e5429f2765a43ce8</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 224, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 593, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 608, in _call_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.81&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>60e35d90e5429f2765a43ce8</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-14 21:27:32</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>60e35d90e5429f2765a43ce8</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 224, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 593, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 608, in _call_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.81&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>60e35d90e5429f2765a43ce8</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-14 21:28:21</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>60e35d90e5429f2765a43ce8</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 260, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduler.py", line 321, in _alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2298, in _start_work_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2889, in start_new_career_session&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 899, in resend_at_work_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.81&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>60e35d90e5429f2765a43ce8</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-14 21:28:21</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>60e35d90e5429f2765a43ce8</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 260, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduler.py", line 321, in _alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2368, in _start_work_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3116, in put_sim_in_career_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 223, in put_sim_in_managed_rabbithole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 171, in _try_put_sim_in_rabbithole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 666, in _setup_uninstantiated_no_travel&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 727, in _on_sim_enter_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 736, in _activate_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\rabbit_hole\career_rabbit_hole.py", line 84, in on_activate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3206, in attend_work&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 899, in resend_at_work_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.81&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>60e35d90e5429f2765a43ce8</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-14 21:28:52</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>60e35d90e5429f2765a43ce8</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 260, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduler.py", line 321, in _alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2298, in _start_work_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2889, in start_new_career_session&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 899, in resend_at_work_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.81&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>60e35d90e5429f2765a43ce8</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-14 21:28:53</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>60e35d90e5429f2765a43ce8</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 260, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduler.py", line 321, in _alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2298, in _start_work_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2889, in start_new_career_session&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 899, in resend_at_work_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.81&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>60e35d90e5429f2765a43ce8</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-14 21:28:56</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>60e35d90e5429f2765a43ce8</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\commands.py", line 399, in invoke_command&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server_commands\ui_commands.py", line 29, in ui_dialog_respond&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\ui\ui_dialog_service.py", line 211, in dialog_respond&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\ui\ui_dialog.py", line 513, in respond&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\callback_utils.py", line 158, in __call__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_service.py", line 452, in _on_career_event_multi_sim_response&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2439, in on_career_event_declined&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3116, in put_sim_in_career_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 223, in put_sim_in_managed_rabbithole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 171, in _try_put_sim_in_rabbithole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 666, in _setup_uninstantiated_no_travel&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 727, in _on_sim_enter_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 736, in _activate_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\rabbit_hole\career_rabbit_hole.py", line 84, in on_activate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3206, in attend_work&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 899, in resend_at_work_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.81&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>60e35d90e5429f2765a43ce8</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-14 21:29:51</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>60e35d90e5429f2765a43ce8</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 260, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduler.py", line 321, in _alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2298, in _start_work_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2889, in start_new_career_session&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 899, in resend_at_work_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.81&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>60e35d90e5429f2765a43ce8</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-14 21:29:51</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>60e35d90e5429f2765a43ce8</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 260, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduler.py", line 321, in _alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2368, in _start_work_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3116, in put_sim_in_career_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 223, in put_sim_in_managed_rabbithole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 171, in _try_put_sim_in_rabbithole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 666, in _setup_uninstantiated_no_travel&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 727, in _on_sim_enter_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 736, in _activate_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\rabbit_hole\career_rabbit_hole.py", line 84, in on_activate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3206, in attend_work&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 899, in resend_at_work_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.81&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>60e35d90e5429f2765a43ce8</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-14 21:30:03</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>60e35d90e5429f2765a43ce8</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 260, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2199, in _late_for_work_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 899, in resend_at_work_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.81&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>60e35d90e5429f2765a43ce8</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-14 21:30:18</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>60e35d90e5429f2765a43ce8</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 224, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 593, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 608, in _call_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.81&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>60e35d90e5429f2765a43ce8</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-14 21:30:20</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>60e35d90e5429f2765a43ce8</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 260, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduler.py", line 321, in _alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2298, in _start_work_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2889, in start_new_career_session&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 899, in resend_at_work_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.81&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>60e35d90e5429f2765a43ce8</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-14 21:30:21</createtime><buildsignature>Local.Unknown.Unknown.1.103.315.1020-1.300.000.175.Release</buildsignature><categoryid>sim_info.py:2589</categoryid><desyncid>60e35d90e5429f2765a43ce8</desyncid><systemconfig/><screenshot/><desyncdata>Exception occurred while attempting to populate a repeated field: (AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\alarms.py", line 260, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduler.py", line 321, in _alarm_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 2368, in _start_work_callback&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3116, in put_sim_in_career_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 223, in put_sim_in_managed_rabbithole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 171, in _try_put_sim_in_rabbithole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 666, in _setup_uninstantiated_no_travel&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 727, in _on_sim_enter_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\rabbit_hole_service.py", line 736, in _activate_rabbit_hole&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\rabbit_hole\career_rabbit_hole.py", line 84, in on_activate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 3206, in attend_work&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\careers\career_base.py", line 899, in resend_at_work_info&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 1096, in notify_dirty&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\server\client.py", line 991, in send_selectable_sims_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 202, in __getattr__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim_info.py", line 2589, in can_care_for_toddler_at_home&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_currently_at_work_career'rtim=0&#13;&#10;Client Session Time: 21.81&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
</root>