<?xml version="1.0" ?><root>
<BetterExceptions><BEversion>v3.11</BEversion><WasBlank>False</WasBlank><TuningLoadFinished>True</TuningLoadFinished><BadObjectCC>True</BadObjectCC><Advice>This is likely due to bad object CC. Check the Summary and Broken Mods section in BE Report.</Advice></BetterExceptions><report><version>2</version><sessionid>cbc31ef5e8daaf3765a6ee5a</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-16 22:20:22</createtime><buildsignature>Local.Unknown.Unknown.1.104.58.1030-1.200.000.618.Release</buildsignature><categoryid>roommate_service.py:1392</categoryid><desyncid>cbc31ef5e8daaf3765a6ee5a</desyncid><systemconfig/><screenshot/><desyncdata>Exception raised while processing zone spin up sequence: 'NoneType' object is not iterable (TypeError: 'NoneType' object is not iterable)&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 130, in wrapped&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 126, in finally_wrap&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 157, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 175, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 383, in c_api_client_connect&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_spin.py", line 100, in _turbolib_on_late_zone_load&#13;&#10;  File "src/control_any_sim/util/inject.py", line 10, in _inject&#13;&#10;  File "src/control_any_sim/util/game_events.py", line 84, in canys_zone_do_zone_spin_up&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 609, in do_zone_spin_up&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 1677, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 307, in on_enter&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\roommate_service.py", line 2142, in initialize_roommates&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\roommate_service.py", line 2278, in _initialize_roommates&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\roommate_service.py", line 2248, in _create_university_roommate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\roommate_service.py", line 1392, in add_roommate&#13;&#10;TypeError: 'NoneType' object is not iterablertim=0&#13;&#10;Client Session Time: 21.66&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>cbc31ef5e8daaf3765a6ee5a</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-16 22:20:53</createtime><buildsignature>Local.Unknown.Unknown.1.104.58.1030-1.200.000.618.Release</buildsignature><categoryid>roommate_service.py:1392</categoryid><desyncid>cbc31ef5e8daaf3765a6ee5a</desyncid><systemconfig/><screenshot/><desyncdata>Exception raised while processing zone spin up sequence: 'NoneType' object is not iterable (TypeError: 'NoneType' object is not iterable)&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 130, in wrapped&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 126, in finally_wrap&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 157, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 175, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 383, in c_api_client_connect&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_spin.py", line 100, in _turbolib_on_late_zone_load&#13;&#10;  File "src/control_any_sim/util/inject.py", line 10, in _inject&#13;&#10;  File "src/control_any_sim/util/game_events.py", line 84, in canys_zone_do_zone_spin_up&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 609, in do_zone_spin_up&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 1677, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 307, in on_enter&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\roommate_service.py", line 2142, in initialize_roommates&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\roommate_service.py", line 2278, in _initialize_roommates&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\roommate_service.py", line 2248, in _create_university_roommate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\services\roommate_service.py", line 1392, in add_roommate&#13;&#10;TypeError: 'NoneType' object is not iterablertim=0&#13;&#10;Client Session Time: 21.66&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>cbc31ef5e8daaf3765a6ee5a</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2024-01-16 23:07:57</createtime><buildsignature>Local.Unknown.Unknown.1.104.58.1030-1.200.000.618.Release</buildsignature><categoryid>tunable.py:146</categoryid><desyncid>cbc31ef5e8daaf3765a6ee5a</desyncid><systemconfig/><screenshot/><desyncdata>Exception when applying action &lt;CreateSituationLootOp ParticipantType.Actor&gt; for loot &lt;class 'sims4.tuning.instances.Pearlv_hiddentrait_SocialInteraction/2364740335'&gt; (AttributeError: 'NoneType' object has no attribute 'get_predefined_guest_list')&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\injector.py", line 26, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\masked\v177c\zone_tick.py", line 83, in _turbolib_zone_game_update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 219, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 335, in _run&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\outcome.py", line 166, in on_loot&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\loot.py", line 157, in apply_operations&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\loot.py", line 595, in apply_to_resolver&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\loot_basic_op.py", line 303, in apply_to_resolver&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\buffs\dynamic_buff_loot_op.py", line 79, in _apply_to_subject_and_target&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 470, in exported_func&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\buff_component.py", line 292, in add_buff_from_op&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\statistics\base_statistic_tracker.py", line 531, in set_max&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\statistics\base_statistic_tracker.py", line 433, in get_statistic&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\statistics\commodity_tracker.py", line 37, in add_statistic&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\statistics\base_statistic_tracker.py", line 357, in add_statistic&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\statistics\commodity.py", line 1089, in __init__&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\statistics\commodity.py", line 1102, in init_appropriate_simulation&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\statistics\commodity.py", line 1283, in on_initial_startup&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\statistics\commodity.py", line 1216, in _setup_commodity_states&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\statistics\commodity.py", line 1637, in _set_state&#13;&#10;  File "E:\Builds\MCCC_2023_7_1\mc_cmd_center\mc_utils.py", line 202, in _wrapper_function&#13;&#10;  File "E:\Builds\MCCC_2023_7_1\mc_cas\mc_cas_inject.py", line 107, in inject_add_buff_from_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\statistics\commodity.py", line 1576, in _add_buff_from_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\__init__.py", line 470, in exported_func&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\objects\components\buff_component.py", line 344, in add_buff&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\buffs\buff.py", line 1215, in on_add&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\buffs\buff.py", line 1263, in apply_all_loot_actions&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\loot.py", line 597, in apply_to_resolver&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\utils\loot_basic_op.py", line 303, in apply_to_resolver&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\situations\tunable.py", line 605, in _apply_to_subject_and_target&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\situations\tunable.py", line 277, in &lt;lambda&gt;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\situations\tunable.py", line 146, in start_situation&#13;&#10;AttributeError: 'NoneType' object has no attribute 'get_predefined_guest_list'rtim=0&#13;&#10;Client Session Time: 21.66&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0x96d01090&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 13,96,0,5609&#13; &#10;Modded: True&#13; &#10;SystemInfo: Windows 10 10.0.19043 GPU: AMD Custom GPU 0405 (RADV VANGOGH) aticfx64.dll 32767.65535.65535.65535, GUID: 00000000-0004-0000-0000-000000000000&#13; &#10;</desyncdata></report>
</root>